name: Baseline
on:
  push:
    branches: [ main, alpha/s0-migration ]
  pull_request:
    branches: [ main, alpha/s0-migration ]

jobs:
  baseline:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Postgres client
        run: sudo apt-get update && sudo apt-get install -y postgresql-client jq

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || echo "No requirements.txt found"

      - name: Start services
        run: |
          cp .env.example .env || echo "No .env.example found"
          docker compose up -d --wait || echo "Docker compose not available"

      - name: Wait for services
        run: sleep 30

      - name: Run baseline
        run: make baseline
        env:
          PGHOST: localhost
          PGPORT: 5432
          PGUSER: postgres
          PGPASSWORD: postgres
          PGDATABASE: mnx_alpha

      - name: Upload baseline artifacts
        uses: actions/upload-artifact@v4
        with:
          name: baseline-${{ github.sha }}
          path: artifacts/baseline/
          retention-days: 30

      - name: Display baseline summary
        run: |
          if [ -f artifacts/baseline/*/hashes/baseline.sha ]; then
            echo "Baseline hash: $(cat artifacts/baseline/*/hashes/baseline.sha)"
          fi
          if [ -f artifacts/baseline/*/staleness.txt ]; then
            echo "Staleness report:"
            cat artifacts/baseline/*/staleness.txt
          fi
